// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CH (
        ap_ready,
        x,
        y,
        z,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] y;
input  [31:0] z;
output  [31:0] ap_return;

wire   [31:0] xor_ln39_fu_34_p2;
wire   [31:0] and_ln39_1_fu_40_p2;
wire   [31:0] and_ln39_fu_28_p2;

assign and_ln39_1_fu_40_p2 = (z & xor_ln39_fu_34_p2);

assign and_ln39_fu_28_p2 = (y & x);

assign ap_ready = 1'b1;

assign ap_return = (and_ln39_fu_28_p2 ^ and_ln39_1_fu_40_p2);

assign xor_ln39_fu_34_p2 = (x ^ 32'd4294967295);

endmodule //CH
