// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module SIG0 (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

wire   [6:0] trunc_ln35_fu_38_p1;
wire   [24:0] lshr_ln_fu_28_p4;
wire   [17:0] trunc_ln35_2_fu_60_p1;
wire   [13:0] lshr_ln35_2_fu_50_p4;
wire   [28:0] lshr_ln5_fu_72_p4;
wire   [31:0] zext_ln55_fu_82_p1;
wire   [31:0] or_ln35_2_fu_64_p3;
wire   [31:0] xor_ln55_fu_86_p2;
wire   [31:0] or_ln_fu_42_p3;

assign ap_ready = 1'b1;

assign ap_return = (xor_ln55_fu_86_p2 ^ or_ln_fu_42_p3);

assign lshr_ln35_2_fu_50_p4 = {{x[31:18]}};

assign lshr_ln5_fu_72_p4 = {{x[31:3]}};

assign lshr_ln_fu_28_p4 = {{x[31:7]}};

assign or_ln35_2_fu_64_p3 = {{trunc_ln35_2_fu_60_p1}, {lshr_ln35_2_fu_50_p4}};

assign or_ln_fu_42_p3 = {{trunc_ln35_fu_38_p1}, {lshr_ln_fu_28_p4}};

assign trunc_ln35_2_fu_60_p1 = x[17:0];

assign trunc_ln35_fu_38_p1 = x[6:0];

assign xor_ln55_fu_86_p2 = (zext_ln55_fu_82_p1 ^ or_ln35_2_fu_64_p3);

assign zext_ln55_fu_82_p1 = lshr_ln5_fu_72_p4;

endmodule //SIG0
