// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CH.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CH::ap_const_logic_1 = sc_dt::Log_1;
const bool CH::ap_const_boolean_1 = true;
const sc_lv<32> CH::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_logic CH::ap_const_logic_0 = sc_dt::Log_0;

CH::CH(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_and_ln39_1_fu_40_p2);
    sensitive << ( z );
    sensitive << ( xor_ln39_fu_34_p2 );

    SC_METHOD(thread_and_ln39_fu_28_p2);
    sensitive << ( x );
    sensitive << ( y );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( and_ln39_1_fu_40_p2 );
    sensitive << ( and_ln39_fu_28_p2 );

    SC_METHOD(thread_xor_ln39_fu_34_p2);
    sensitive << ( x );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CH_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, y, "(port)y");
    sc_trace(mVcdFile, z, "(port)z");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, xor_ln39_fu_34_p2, "xor_ln39_fu_34_p2");
    sc_trace(mVcdFile, and_ln39_1_fu_40_p2, "and_ln39_1_fu_40_p2");
    sc_trace(mVcdFile, and_ln39_fu_28_p2, "and_ln39_fu_28_p2");
#endif

    }
}

CH::~CH() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void CH::thread_and_ln39_1_fu_40_p2() {
    and_ln39_1_fu_40_p2 = (z.read() & xor_ln39_fu_34_p2.read());
}

void CH::thread_and_ln39_fu_28_p2() {
    and_ln39_fu_28_p2 = (y.read() & x.read());
}

void CH::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void CH::thread_ap_return() {
    ap_return = (and_ln39_1_fu_40_p2.read() ^ and_ln39_fu_28_p2.read());
}

void CH::thread_xor_ln39_fu_34_p2() {
    xor_ln39_fu_34_p2 = (x.read() ^ ap_const_lv32_FFFFFFFF);
}

}

